# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d0a330179605136e59cbcc18191a6aae101ee271651e74fe4a87c3cdcac91c938b5942d90abc4935cec0abe7c658779b46338a255c25ce53fa583294282ff86e

test:
  secret_key_base: 2856ae92e515ed3465260678df96c7438e45be679d5b4eeaee4a69b9e00067f24922de6ef562b6daaa129872f007cf80119cdb0f3c859efd39c64ec77d104c8f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
